"""
report_generator.py — Multi-Format Report Generation

Generates review reports in JSON, Markdown, and SARIF formats from
pipeline findings.

Usage (as module):
    from pipeline.report_generator import generate_markdown_report, generate_sarif_report
    md = generate_markdown_report(report)
    sarif = generate_sarif_report(report)
"""

import json
import datetime
from typing import Dict, List, Optional
from collections import defaultdict

from pipeline.deduplication import (
    group_findings_by_file,
    group_findings_by_category,
    severity_rank,
)


# ── Markdown Report ──────────────────────────────────────────────────────────

def generate_markdown_report(report, include_fixes: bool = True) -> str:
    """
    Generate a human-readable Markdown report from a RepositoryReport.

    Args:
        report: RepositoryReport dataclass or dict with findings.
        include_fixes: Whether to include suggested fix code blocks.

    Returns:
        Markdown string.
    """
    # Support both dataclass and dict
    if hasattr(report, "__dict__") and not isinstance(report, dict):
        from dataclasses import asdict
        report = asdict(report)

    lines = []
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Header ──
    lines.append(f"# Go Code Review Report")
    lines.append(f"")
    lines.append(f"**Repository:** `{report.get('repo_path', 'unknown')}`")
    lines.append(f"**Date:** {now}")
    lines.append(f"**Mode:** {report.get('config', {}).get('mode', 'hybrid')}")
    lines.append(f"**Duration:** {report.get('elapsed_seconds', 0)}s")
    lines.append(f"")

    # ── Summary ──
    summary = report.get("summary", {})
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Files reviewed | {report.get('total_files', 0)} |")
    lines.append(f"| Code chunks analyzed | {report.get('total_chunks', 0)} |")
    lines.append(f"| Total findings | {report.get('total_findings', 0)} |")
    lines.append(f"| Critical | {summary.get('critical', 0)} |")
    lines.append(f"| High | {summary.get('high', 0)} |")
    lines.append(f"| Medium | {summary.get('medium', 0)} |")
    lines.append(f"| Low | {summary.get('low', 0)} |")
    lines.append(f"| Info | {summary.get('info', 0)} |")
    lines.append(f"")

    findings = report.get("findings", [])

    if not findings:
        lines.append("> **No violations found.** The code looks clean!")
        return "\n".join(lines)

    # ── Critical & High Findings ──
    critical_high = [f for f in findings if f.get("severity", "").upper() in ("CRITICAL", "HIGH")]
    if critical_high:
        lines.append(f"## Critical & High Severity Issues")
        lines.append(f"")
        lines.append(f"> These issues should be addressed before merging.")
        lines.append(f"")
        for finding in critical_high:
            lines.extend(_format_finding_md(finding, include_fixes))
            lines.append(f"")

    # ── By File ──
    lines.append(f"## Findings by File")
    lines.append(f"")

    by_file = group_findings_by_file(findings)
    for file_path in sorted(by_file.keys()):
        file_findings = by_file[file_path]
        severity_counts = _severity_summary(file_findings)
        lines.append(f"### `{file_path}` ({len(file_findings)} issues: {severity_counts})")
        lines.append(f"")

        for finding in sorted(file_findings, key=lambda f: severity_rank(f.get("severity", "LOW"))):
            lines.extend(_format_finding_md(finding, include_fixes))
            lines.append(f"")

    # ── By Category ──
    lines.append(f"## Findings by Category")
    lines.append(f"")

    by_category = group_findings_by_category(findings)
    for category in sorted(by_category.keys()):
        cat_findings = by_category[category]
        lines.append(f"### {category.replace('_', ' ').title()} ({len(cat_findings)} issues)")
        lines.append(f"")
        lines.append(f"| Rule | Severity | File | Description |")
        lines.append(f"|------|----------|------|-------------|")
        for f in cat_findings:
            desc = f.get("description", "")[:80].replace("|", "\\|")
            lines.append(
                f"| {f.get('rule_id', '')} | {f.get('severity', '')} "
                f"| `{f.get('file', '')}:{f.get('line_start', '')}` | {desc} |"
            )
        lines.append(f"")

    # ── Footer ──
    lines.append(f"---")
    lines.append(f"*Generated by Go Code Reviewer — {now}*")

    return "\n".join(lines)


def _format_finding_md(finding: Dict, include_fixes: bool = True) -> List[str]:
    """Format a single finding as Markdown."""
    lines = []

    severity = finding.get("severity", "LOW")
    icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}.get(severity, "⚪")

    lines.append(
        f"#### {icon} [{finding.get('rule_id', 'N/A')}] {severity} — {finding.get('title', 'Untitled')}"
    )

    file_ref = finding.get("file", "")
    if finding.get("line_start"):
        file_ref += f":{finding['line_start']}"
    lines.append(f"- **File:** `{file_ref}`")

    if finding.get("function"):
        lines.append(f"- **Function:** `{finding['function']}`")

    if finding.get("effort") and finding["effort"] != "unknown":
        lines.append(f"- **Fix effort:** {finding['effort']}")

    if finding.get("auto_fixable"):
        lines.append(f"- **Auto-fixable:** ✅ Yes")

    lines.append(f"")
    lines.append(finding.get("description", ""))

    if finding.get("current_code"):
        lines.append(f"")
        lines.append(f"**Current code:**")
        lines.append(f"```go")
        lines.append(finding["current_code"])
        lines.append(f"```")

    if include_fixes and finding.get("suggested_fix"):
        lines.append(f"")
        lines.append(f"**Suggested fix:**")
        lines.append(f"```go")
        lines.append(finding["suggested_fix"])
        lines.append(f"```")

    return lines


def _severity_summary(findings: List[Dict]) -> str:
    """Create a compact severity summary string."""
    counts = defaultdict(int)
    for f in findings:
        counts[f.get("severity", "LOW").upper()] += 1

    parts = []
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        if counts.get(sev, 0) > 0:
            parts.append(f"{counts[sev]} {sev.lower()}")
    return ", ".join(parts) if parts else "none"


# ── JSON Report ──────────────────────────────────────────────────────────────

def generate_json_report(report) -> str:
    """
    Generate a JSON report string from a RepositoryReport.
    """
    if hasattr(report, "__dict__") and not isinstance(report, dict):
        from dataclasses import asdict
        report = asdict(report)

    return json.dumps(report, indent=2, default=str, ensure_ascii=False)


# ── SARIF Report ─────────────────────────────────────────────────────────────

def generate_sarif_report(report) -> Dict:
    """
    Generate a SARIF v2.1.0 report for integration with GitHub/GitLab.

    SARIF (Static Analysis Results Interchange Format) is the standard
    format for static analysis tool output.

    Ref: https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html
    """
    if hasattr(report, "__dict__") and not isinstance(report, dict):
        from dataclasses import asdict
        report = asdict(report)

    findings = report.get("findings", [])

    # Build unique rules list
    rules_map = {}
    for finding in findings:
        rule_id = finding.get("rule_id", "UNKNOWN")
        if rule_id not in rules_map:
            rules_map[rule_id] = {
                "id": rule_id,
                "name": finding.get("title", rule_id),
                "shortDescription": {
                    "text": finding.get("title", rule_id),
                },
                "fullDescription": {
                    "text": finding.get("description", "")[:500],
                },
                "defaultConfiguration": {
                    "level": _sarif_level(finding.get("severity", "LOW")),
                },
                "properties": {
                    "category": finding.get("category", "general"),
                },
            }

    rules = list(rules_map.values())
    rule_index = {r["id"]: i for i, r in enumerate(rules)}

    # Build results
    results = []
    for finding in findings:
        rule_id = finding.get("rule_id", "UNKNOWN")
        file_path = finding.get("file", "unknown").replace("\\", "/")
        line_start = max(finding.get("line_start", 1), 1)
        line_end = max(finding.get("line_end", line_start), line_start)

        result = {
            "ruleId": rule_id,
            "ruleIndex": rule_index.get(rule_id, 0),
            "level": _sarif_level(finding.get("severity", "LOW")),
            "message": {
                "text": finding.get("description", "Code review finding"),
            },
            "locations": [
                {
                    "physicalLocation": {
                        "artifactLocation": {
                            "uri": file_path,
                            "uriBaseId": "%SRCROOT%",
                        },
                        "region": {
                            "startLine": line_start,
                            "endLine": line_end,
                        },
                    },
                },
            ],
        }

        # Add fix if available
        if finding.get("suggested_fix"):
            result["fixes"] = [
                {
                    "description": {
                        "text": f"Apply suggested fix for {rule_id}",
                    },
                    "artifactChanges": [
                        {
                            "artifactLocation": {
                                "uri": file_path,
                                "uriBaseId": "%SRCROOT%",
                            },
                            "replacements": [
                                {
                                    "deletedRegion": {
                                        "startLine": line_start,
                                        "endLine": line_end,
                                    },
                                    "insertedContent": {
                                        "text": finding["suggested_fix"],
                                    },
                                },
                            ],
                        },
                    ],
                },
            ]

        results.append(result)

    sarif = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "go-code-reviewer",
                        "version": "1.0.0",
                        "informationUri": "https://github.com/your-org/go-code-reviewer",
                        "rules": rules,
                    },
                },
                "results": results,
                "invocations": [
                    {
                        "executionSuccessful": True,
                        "endTimeUtc": datetime.datetime.utcnow().isoformat() + "Z",
                        "properties": {
                            "reviewMode": report.get("config", {}).get("mode", "hybrid"),
                            "elapsedSeconds": report.get("elapsed_seconds", 0),
                            "filesReviewed": report.get("total_files", 0),
                        },
                    },
                ],
            },
        ],
    }

    return sarif


def _sarif_level(severity: str) -> str:
    """Map severity to SARIF level."""
    mapping = {
        "CRITICAL": "error",
        "HIGH": "error",
        "MEDIUM": "warning",
        "LOW": "note",
        "INFO": "note",
    }
    return mapping.get(severity.upper(), "warning")


# ── GitHub PR Comment ────────────────────────────────────────────────────────

def generate_pr_comment(report, max_findings: int = 20) -> str:
    """
    Generate a concise Markdown comment suitable for posting as a
    GitHub PR review comment.
    """
    if hasattr(report, "__dict__") and not isinstance(report, dict):
        from dataclasses import asdict
        report = asdict(report)

    findings = report.get("findings", [])
    summary = report.get("summary", {})

    lines = []
    lines.append("## 🔍 Go Code Review Results")
    lines.append("")

    total = summary.get("total", len(findings))
    critical = summary.get("critical", 0)
    high = summary.get("high", 0)

    if total == 0:
        lines.append("✅ **No violations found.** Great job!")
        return "\n".join(lines)

    # Status badge
    if critical > 0:
        lines.append(f"🔴 **{total} issues found** ({critical} critical, {high} high)")
    elif high > 0:
        lines.append(f"🟠 **{total} issues found** ({high} high)")
    else:
        lines.append(f"🟡 **{total} issues found** (no critical/high)")

    lines.append("")
    lines.append("<details>")
    lines.append("<summary>Click to expand findings</summary>")
    lines.append("")

    shown = findings[:max_findings]
    for finding in shown:
        severity = finding.get("severity", "LOW")
        icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}.get(severity, "⚪")
        file_ref = finding.get("file", "")
        if finding.get("line_start"):
            file_ref += f":{finding['line_start']}"

        lines.append(f"- {icon} **[{finding.get('rule_id', '')}]** {finding.get('title', '')} — `{file_ref}`")

    if len(findings) > max_findings:
        lines.append(f"")
        lines.append(f"*...and {len(findings) - max_findings} more findings. See full report for details.*")

    lines.append("")
    lines.append("</details>")
    lines.append("")
    lines.append(f"*Reviewed {report.get('total_files', 0)} files in {report.get('elapsed_seconds', 0)}s*")

    return "\n".join(lines)

